name: docker build
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
      with:
        sparse-checkout: |
          docker_make
        sparse-checkout-cone-mode: false
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DYN_ACC_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DYN_SEC_ACC_KEY }}
          aws-region: ap-northeast-1

      run: |
        mv ./docker_make/* ./

        aws ecr-public get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin public.ecr.aws/z1y9t7d1

        docker build -t some_selenium_pack .
        docker tag some_selenium_pack:latest public.ecr.aws/z1y9t7d1/some_selenium_pack:latest
        docker push public.ecr.aws/z1y9t7d1/some_selenium_pack:latest
        