name: MeCab try
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        # if: false
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: lib setup
        # if: false
        run: |
          pip install mecab-python3
          pip install ipadic

          python << 'EOF'
          import MeCab
          import ipadic

          mecab = MeCab.Tagger(ipadic.MECAB_ARGS)
          print(mecab.parse("ここは地球上の日本です。"))

          EOF

      - name: NEologd setup
        run: |
          git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
          cd mecab-ipadic-neologd
          ./bin/install-mecab-ipadic-neologd -n -a