name: "multiple account flw"
on: workflow_dispatch
## scheduled at every hour
##  schedule:
##    - cron: '29 * * * *'

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: setup
        run: |
          npm install twitter-api-sdk

      - run: |
          npm start
           
          ls -la
        env:
          BEARER_TOKEN: ${{ secrets.TWT_BEARER_TOKEN }}
          ACC_KEY: ${{ secrets.AWS_DYN_ACC_KEY }}
          SEC_ACC_KEY: ${{ secrets.AWS_DYN_SEC_ACC_KEY }}

      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: raw_csvs
          path: |
            ./*.csv

  make_figures:
    needs: get_data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: [pj_sekai, bang_dream_gbp, Genshin_7]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - uses: actions/download-artifact@v3
        with:
          name: raw_csvs
      
      - name: setup
        run: |
          for fname in *_${{ matrix.account }}.csv; do
            mv $fname ${fname%_${{ matrix.account }}.csv}.csv
          done
        
      - name: main run
        continue-on-error: true
        run: |
          sudo apt-get update
          sudo apt-get install fonts-ipaexfont
          pip install matplotlib
          pip install pandas
          pip install statsmodels

          python ./scripts/see_res_1min.py
          python ./scripts/make_stats_1min.py
        env:
          ACCOUNT: ${{ matrix.account }}

      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: |
            ./*.csv
            ./*.png
          name: ${{ matrix.account }}_data

  make_merged_figure:
    needs: make_figures
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - uses: actions/download-artifact@v3

      - name: setup
        run: |
          for datapath in $(find ./  -maxdepth 1 -type d -name '*_data'); do
            echo ${datapath}" folder found!"
            mv ${datapath}/trend_diff.csv ./trend_diff_${datapath%_data}.csv            
            mv ${datapath}/trend_diff.csv ./res_diff_${datapath%_data}.csv
          done

          ls -la

      