name: send artifact try
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "2023/01/04 was a good day!" > goodday.txt
      - uses: actions/upload-artifact@v3
        with:
          path: ./goodday.txt
      - name: main
        run: |
          curl -XPOST -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
          -d '{"ref": "master", "inputs": {"rid": "${{ github.run_id }}"}}'
          "https://github.com/repos/popcube/prosekacube/actions/workflows/28501413/dispatches"
