name: one-time migration
on: workflow_dispatch

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          node ./scripts/temp_migration_script.js
        
