name: just test
on: workflow_dispatch
## scheduled at every hour
##  schedule:
##    - cron: '29 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
          "https://twitter.com/elonmusk/status/1692431667548528661"
