name: just test
on: workflow_dispatch
## scheduled at every hour
##  schedule:
##    - cron: '29 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -b my.cookie -c my.cookie -L \
          "https://twitter.com/pj_sekai/status/1667051397773422594"
