name: "single account flow"
on:
  workflow_dispatch:
    inputs:
      account:
        description: 'select twitter account name'
        required: true
        default: 'pj_sekai'
        type: choice
        options:
        - pj_sekai
        - bang_dream_gbp
        - Genshin_7
        - wds_game
        - ensemble_stars

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

## scheduled at every hour
##  schedule:
##    - cron: '29 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup
        run: |
          npm install twitter-api-sdk
       
      - run: |
          npm start
           
          ls -la
        env:
          BEARER_TOKEN: ${{ secrets.TWT_BEARER_TOKEN }}
          ACC_KEY: ${{ secrets.AWS_DYN_ACC_KEY }}
          SEC_ACC_KEY: ${{ secrets.AWS_DYN_SEC_ACC_KEY }}
          ACCOUNT: ${{ inputs.account }}
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        
      - name: main run
        continue-on-error: true
        run: |
          sudo apt-get update
          sudo apt-get install fonts-ipaexfont          
          pip install --upgrade pip --quiet
          pip install matplotlib --quiet
          pip install pandas --quiet
          pip install scipy --quiet
          pip install lxml --quiet
          pip install html5lib --quiet
          pip install bs4 --quiet
          pip install requests --quiet
          pip install statsmodels --quiet

          python ./scripts/see_res_1min.py
          python ./scripts/make_stats_1min.py

      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: |
            ./*.csv
            ./*.png
