name: "twt api test"
on: workflow_dispatch
## scheduled at every hour
##  schedule:
##    - cron: '29 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup
        run: |
          npm install twitter-api-sdk
       
      - run: |
          npm start
           
          ls -la
        env:
          BEARER_TOKEN: ${{ secrets.TWT_BEARER_TOKEN }}
          ACC_KEY: ${{ secrets.AWS_DYN_ACC_KEY }}
          SEC_ACC_KEY: ${{ secrets.AWS_DYN_SEC_ACC_KEY }}
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        
      - run: |
          pip install matplotlib
          pip install pandas
          python ./scripts/see_res_1min.py

      - uses: actions/upload-artifact@v3
        with:
          path: |
            ./results.csv
            ./*.png
