name: twt api test
on: [push, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
#      - run: |
#          curl -H "Authorization: Bearer ${{ secrets.TWT_BEARER_TOKEN }}" \
#          https://api.twitter.com/2/users/by/username/pj_sekai?user.fields=public_metrics

       - uses: actions/checkout@v3

       - name: setup
         run: |
           npm install twitter-api-sdk
       
       - run: |
           npm start
         env:
           BEARER_TOKEN: ${{ secrets.TWT_BEARER_TOKEN }}
           ACC_KEY: ${{ secrets.AWS_DYN_ACC_KEY }}
           SEC_ACC_KEY: ${{ secrets.AWS_DYN_SEC_ACC_KEY }}
